-- ChatGPT
return {}
-- return {
--   "jackMort/ChatGPT.nvim",
--   event = "VeryLazy",
--   config = function()
--     require("chatgpt").setup()
--   end,
--   dependencies = {
--     "MunifTanjim/nui.nvim",
--     "nvim-lua/plenary.nvim",
--     "nvim-telescope/telescope.nvim"
--   }
--   config = function()
--     require("chatgpt").setup({
--       -- api_key_cmd = "op read op://private/OpenAI/credential --no-newline"
--       -- api_key_cmd = "gpg --decrypt ~/secret.txt.gpg 2>/dev/null"
--     })
--   end
-- }
