#!/usr/bin/python3

import datetime
import math
import os

name = "Yang"
birthday = "1990-10-01"
os.system(f"cowsay Hello, {name}!")
print(f"\nYour birthday is {birthday}")
bday = datetime.datetime.strptime(birthday, "%Y-%m-%d")
today = datetime.datetime.now()
print(f"You have lived {(str(today - bday).split(','))[0]}.")

delta_t = 5000
# specialDay = []

for i in range(1, 7):
    x = bday + datetime.timedelta(days=delta_t * i)
    # specialDay.append(x)
    print(f"{str(delta_t * i)} day of your life {str(x).split(' ')[0]}")

ages = [70, 80, 90]
for x in ages:
    die = bday + datetime.timedelta(weeks=x * 52)
    days_left = str(die - today).split(" ")[0]
    print(
        f"{days_left} days / {str(math.floor(int(days_left) / 7))} weeks left if live to {str(x)}."
    )
